//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookRentalList
    {
        public long BookID { get; set; }
        public long BookRentalID { get; set; }
        public Nullable<long> No { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual BookRentalHitory BookRentalHitory { get; set; }
    }
}
